yarnPath: .yarn/releases/yarn-4.2.2.cjs

nodeLinker: pnp

pnpMode: strict

enableGlobalCache: true

compressionLevel: mixed

enableImmutableInstalls: false

preferInteractive: true

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard

packageExtensions:
  "@types/react@*":
    peerDependencies:
      react: "*"
