/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal'
export namespace Components {
  interface AnnDialog {}
  interface AnnNodeSelect {}
  interface AnnSelection {}
  interface AnnShare {}
  interface MyComponent {
    /**
     * The first name
     */
    first: string
    /**
     * The last name
     */
    last: string
    /**
     * The middle name
     */
    middle: string
  }
}
declare global {
  interface HTMLAnnDialogElement extends Components.AnnDialog, HTMLStencilElement {}
  var HTMLAnnDialogElement: {
    prototype: HTMLAnnDialogElement
    new (): HTMLAnnDialogElement
  }
  interface HTMLAnnNodeSelectElement extends Components.AnnNodeSelect, HTMLStencilElement {}
  var HTMLAnnNodeSelectElement: {
    prototype: HTMLAnnNodeSelectElement
    new (): HTMLAnnNodeSelectElement
  }
  interface HTMLAnnSelectionElement extends Components.AnnSelection, HTMLStencilElement {}
  var HTMLAnnSelectionElement: {
    prototype: HTMLAnnSelectionElement
    new (): HTMLAnnSelectionElement
  }
  interface HTMLAnnShareElement extends Components.AnnShare, HTMLStencilElement {}
  var HTMLAnnShareElement: {
    prototype: HTMLAnnShareElement
    new (): HTMLAnnShareElement
  }
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement
    new (): HTMLMyComponentElement
  }
  interface HTMLElementTagNameMap {
    'ann-dialog': HTMLAnnDialogElement
    'ann-node-select': HTMLAnnNodeSelectElement
    'ann-selection': HTMLAnnSelectionElement
    'ann-share': HTMLAnnShareElement
    'my-component': HTMLMyComponentElement
  }
}
declare namespace LocalJSX {
  interface AnnDialog {}
  interface AnnNodeSelect {}
  interface AnnSelection {}
  interface AnnShare {}
  interface MyComponent {
    /**
     * The first name
     */
    first?: string
    /**
     * The last name
     */
    last?: string
    /**
     * The middle name
     */
    middle?: string
  }
  interface IntrinsicElements {
    'ann-dialog': AnnDialog
    'ann-node-select': AnnNodeSelect
    'ann-selection': AnnSelection
    'ann-share': AnnShare
    'my-component': MyComponent
  }
}
export { LocalJSX as JSX }
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'ann-dialog': LocalJSX.AnnDialog & JSXBase.HTMLAttributes<HTMLAnnDialogElement>
      'ann-node-select': LocalJSX.AnnNodeSelect & JSXBase.HTMLAttributes<HTMLAnnNodeSelectElement>
      'ann-selection': LocalJSX.AnnSelection & JSXBase.HTMLAttributes<HTMLAnnSelectionElement>
      'ann-share': LocalJSX.AnnShare & JSXBase.HTMLAttributes<HTMLAnnShareElement>
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>
    }
  }
}
