name: Build Extension

on:
  push:
    branches:
      - main

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build extension
        run: yarn run ext:build

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-output
          path: apps/extension/.output/
