name: Build Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-extension:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build extension
        run: yarn run ext:build

      - name: Zip extension for Chrome
        run: |
          cd apps/extension
          yarn zip
        
      - name: Zip extension for Firefox
        run: |
          cd apps/extension
          yarn zip:firefox

      - name: Upload Chrome extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: apps/extension/.output/*-*-chrome.zip
          retention-days: 30

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: apps/extension/.output/*-*-firefox.zip
          retention-days: 30
